{
 "title": "gobench",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CLIENT - latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(request_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p95-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(request_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p90-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(request_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p50-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(request_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p99-{{method}}"
    }
   ]
  },
  {
   "title": "APP - latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(app_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p95-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(app_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p90-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(app_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p50-{{method}}"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(app_duration_seconds_bucket[1m])))by(method)",
     "legendFormat": "p99-{{method}}"
    }
   ]
  },
  {
   "title": "CLIENT - Request and error rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(request_errors[1m]))by(code)",
     "legendFormat": "{{code}}-errors"
    },
    {
     "expr": "rate(request_duration_seconds_count[1m])",
     "legendFormat": "{{method}}-count"
    }
   ]
  },
  {
   "title": "APP - Request and error rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(app_errors[1m]))by(method)",
     "legendFormat": "errors-{{method}}"
    },
    {
     "expr": "sum(rate(app_duration_seconds_count[1m]))by(method)",
     "legendFormat": "count-{{method}}"
    }
   ]
  },
  {
   "title": "by server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "APP - latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(app_duration_seconds_bucket[1m]))",
       "legendFormat": "{{instance}}-p95"
      },
      {
       "expr": "histogram_quantile(0.9, rate(app_duration_seconds_bucket[1m]))",
       "legendFormat": "{{instance}}-p90"
      },
      {
       "expr": "histogram_quantile(0.5, rate(app_duration_seconds_bucket[1m]))",
       "legendFormat": "{{instance}}-p50"
      },
      {
       "expr": "histogram_quantile(0.99, rate(app_duration_seconds_bucket[1m]))",
       "legendFormat": "{{instance}}-p99"
      }
     ]
    }
   ]
  }
 ]
}